name: Greenbrook Inn
author: Greenbrook Inn
baseurl: 
description: Fairfield County's Premier Inn
email: members[at]greenbrook.me
location: 42°2'16"N   70°12'47"W

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
