name: Greenbrook Inn
author: Greenbrook Inn
baseurl: 
description: New York's Premier Inn
email: greenbrookinn[at]gmail.com
location: 42°2'16"N   70°12'47"W

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
